message(STATUS "CMAKE module path: ${CMAKE_MODULE_PATH}")

function(add_general_compiler_flags)
    morph_flag(-target ve-linux)
    morph_flag(-fno-vectorize)
    morph_flag(-fno-slp-vectorize)
#    morph_flag(-mllvm)
#    morph_flag(-llvm-loopvec=false)
#    morph_flag(-Xclang)
#    morph_flag(-load)
#    morph_flag(-Xclang libRV.so)
#    morph_flag(-mllvm)
#    morph_flag(-rv)
endfunction()

function(add_analysis_compiler_flags)
    morph_flag(-Werror)
    morph_flag(-pedantic)
    morph_flag(-Wall)
    morph_flag(-Wextra)
    morph_flag(-Wno-ignored-attributes)
    morph_flag(-Wno-comment)
endfunction()

function(add_optimization_compiler_flags)
    IF(CMAKE_BUILD_TYPE MATCHES Debug)
        morph_flag(-g)
        morph_flag(-O1)
        message(STATUS "MorphStore is configured in DEBUG mode.")
    ELSEIF(CMAKE_BUILD_TYPE MATCHES Release)
        morph_flag(-O2)
        message(STATUS "MorphStore is configured in RELEASE mode.")
    ELSEIF(CMAKE_BUILD_TYPE MATCHES HighPerf)
        morph_flag(-O3)
        morph_flag(-flto)
        message(STATUS "MorphStore is configured in HIGH PERFORMANCE mode.")
    ELSE(CMAKE_BUILD_TYPE MATCHES Debug)
        message( SEND_ERROR "No known build type specified. Use either Debug, Release or HighPerf" )
    ENDIF(CMAKE_BUILD_TYPE MATCHES Debug)
endfunction()

function(add_vectorization_flags)
    morph_flag(-DAURORATSUBASALLVM)
endfunction()
