function(add_general_compiler_flags)
    morph_flag(-march=native)
    morph_flag(-fstack-protector-all)
endfunction()

function(add_analysis_compiler_flags)
    morph_flag(-Werror)
    morph_flag(-pedantic)
    morph_flag(-Wall)
    morph_flag(-Wextra)
    morph_flag(-Wno-ignored-attributes)
    morph_flag(-Wno-comment)
endfunction()

function(add_optimization_compiler_flags)
    IF(CMAKE_BUILD_TYPE MATCHES Debug)
        morph_flag(-g)
        message(STATUS "MorphStore is configured in DEBUG mode.")
    ELSEIF(CMAKE_BUILD_TYPE MATCHES Release)
        morph_flag(-O2)
        message(STATUS "MorphStore is configured in RELEASE mode.")
    ELSEIF(CMAKE_BUILD_TYPE MATCHES HighPerf)
        morph_flag(-O3)
        morph_flag(-flto)
        message(STATUS "MorphStore is configured in HIGH PERFORMANCE mode.")
    ELSE(CMAKE_BUILD_TYPE MATCHES Debug)
        message( SEND_ERROR "No known build type specified. Use either Debug, Release or HighPerf" )
    ENDIF(CMAKE_BUILD_TYPE MATCHES Debug)
endfunction()

function(add_vectorization_flags)
    morph_flag(-fno-tree-vectorize)
    IF(CSSE)
        morph_flag(-DSSE)
        morph_flag(-msse4.2)
        message(STATUS "SSE4.2 support switched on")
    ENDIF(CSSE)

    IF(CAVXTWO)
      morph_flag(-DSSE)
        morph_flag(-DAVXTWO)
        morph_flag(-mavx2)
        message(STATUS "AVX2 support switched on")
    ENDIF(CAVXTWO)

    IF(CAVX512)
      morph_flag(-DSSE)
        morph_flag(-DAVX512)
        morph_flag(-mavx512f)
        morph_flag(-mavx512pf)
        morph_flag(-mavx512er)
        morph_flag(-mavx512cd)
        morph_flag(-mavx512vl)
        morph_flag(-DAVXTWO)
        morph_flag(-mavx2)
        message(STATUS "AVX512 and AVX2 support switched on")
    ENDIF(CAVX512)
endfunction()