function(add_general_compiler_flags)
    morph_flag(-report-all)
    morph_flag(-fdiag-vector=2)
    morph_flag(-fdiag-parallel=2)
    morph_flag(-fdiag-inline=2)
    morph_flag(-fdiag-system-header)
    morph_flag(-assembly-list)
    morph_flag(-Bstatic)
    morph_flag(-static)
    morph_flag(-v)
endfunction()

function(add_analysis_compiler_flags)
    morph_flag(-Werror)
    morph_flag(-pedantic)
    morph_flag(-Wall)
    morph_flag(-Wextra)
    morph_flag(-Wno-ignored-attributes)
    morph_flag(-Wno-comment)
endfunction()

function(add_optimization_compiler_flags)
    IF(CMAKE_BUILD_TYPE MATCHES Debug)
        morph_flag(-g)
        morph_flag(-proginf)
        morph_flag(-traceback)
        morph_flag(-ftrace)
        morph_flag(-O1)
        message(STATUS "MorphStore is configured in DEBUG mode.")
    ELSEIF(CMAKE_BUILD_TYPE MATCHES Release)
        morph_flag(-O2)
        message(STATUS "MorphStore is configured in RELEASE mode.")
    ELSEIF(CMAKE_BUILD_TYPE MATCHES HighPerf)
        morph_flag(-O3)
        morph_flag(-finline)
        morph_flag(-finline-functions)
        morph_flag(-fipa)
        message(STATUS "MorphStore is configured in HIGH PERFORMANCE mode.")
    ELSE(CMAKE_BUILD_TYPE MATCHES Debug)
        message( SEND_ERROR "No known build type specified. Use either Debug, Release or HighPerf" )
    ENDIF(CMAKE_BUILD_TYPE MATCHES Debug)
endfunction()

function(add_vectorization_flags)
    morph_flag(-mvector)
endfunction()


