macro(enableSSE target)
    target_compile_options(${target} PUBLIC -msse4.2)
    target_compile_definitions(${target} PUBLIC SSE)
    message(STATUS "Enabled SSE for ${target}")
endmacro()

macro(enableAVX2 target)
    target_compile_options(${target} PUBLIC -mavx2)
    target_compile_definitions(${target} PUBLIC SSE AVXTWO)
    message(STATUS "Enabled AVX2 for ${target}")
endmacro()

macro(enableAVX512 target)
    target_compile_options(${target} PUBLIC -mavx512f -mavx512pf -mavx512er -mavx512cd -mavx512vl -mavx2)
    target_compile_definitions(${target} PUBLIC SSE AVXTWO AVX512)
    message(STATUS "Enabled AVX512 for ${target}")
endmacro()

macro(enableNEON target)
#    target_compile_options(${target} PUBLIC -mfpu=neon-vfpv3 -flax-vector-conversions -march=armv8-a+simd)
    target_compile_options(${target} PUBLIC -flax-vector-conversions -march=armv8-a+simd)
    target_compile_definitions(${target} PUBLIC NEON)
    message(STATUS "Enabled Neon for ${target}")
endmacro()
